/*Create a class complex which stores real and imaginary part of a complex
number. Include all types of constructors and destructor. The destructor should
display a message about the destructor being invoked. Create objects using
different constructors and display them*/
#include <iostream>
using name space std;
class complex
{
    float real;
    float imag;
    public:
    void getdata(float a , float b)
    {
        real=a;
        imag=b;
    }
    as

};